#!/usr/bin/env python

import sys
import crypt
import argparse


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('-p', '--password', type=str, required=True,
                        help="plain text password")
    parser.add_argument('-m', '--method', type=str, default='SHA512',
                        help="encrypt method options [MD5, SHA256, SHA512]")
    args = parser.parse_args()

    method = args.method
    password = args.password

    encryptor = Encrypt(sys.version_info[0])
    encryptor.encrypt(password, method)


class Encrypt(object):
    def __init__(self, version):
        self.version = version
        if self.version != 3:
            print('Requirement not match: python >= 3')
            sys.exit(1)
        self.options = {'MD5': crypt.METHOD_MD5,
                        'SHA512': crypt.METHOD_SHA512,
                        'SHA256': crypt.METHOD_SHA256}

    def encrypt(self, password, method):
        try:
            print(crypt.crypt(password, crypt.mksalt(self.options[method])))
        except KeyError:
            print('Method not accepted:', self.method)


if __name__ == '__main__':
    main()
